# Generated by Django 5.0.6 on 2024-06-16 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('skin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='skin_name',
        ),
        migrations.AddField(
            model_name='comments',
            name='skin',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='skin.skins'),
        ),
    ]
