# Generated by Django 5.0.6 on 2024-06-21 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_remove_comments_skin_name_comments_skin'),
        ('skin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skins',
            name='comments',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='comments.comments'),
        ),
    ]
